### ISSUE TITLE
Sapnish

### ISSUE THREAD

**Issue by oscarperpinan** [ClaudiaGEscribano/ClaudiaGEscribano.github.io#1]
Así que das el salto a tener página web. Bien hecho 👍
Me ha sorprendido el apartado de idiomas. No conocía yo el Sapnish. Ya me dirás como es 😆

**Comment by ClaudiaGEscribano** [comment]
Jajaj, es que es un dialecto de mi pueblo. Gracias por el apunte!
Pues estoy de pruebas con ella. Necesitaba un cv para pedir dinero (cómo no) y me ha parecido la mejor manera.
